name: Node.js CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      MAX:
        description: 'Max of number to random'
        required: false
      MAX_LENGTH:
        description: 'Max of number per sequence'
        required: false
      SEQUENCES:
        description: 'Number of sequence generated'
        required: false
        
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION_APP: ${{ github.event.inputs.VERSION }}
      BUILD_NUMBER: ${{ github.event.inputs.BUILD_NUMBER }}
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: node index.js
